### ISSUE TITLE
pybullet.error: number of forces should match the joint indices

### ISSUE THREAD

**Issue by raess1** [HitSZwang/mini_cheetah_pybullet#1]
Hi!
See attached picture for refrence. 
![Skärmklipp](https://user-images.githubusercontent.com/6362413/99772657-799e8a80-2b0b-11eb-9687-68a4a0d3435c.PNG)

**Comment by HitSZwang** [comment]
(1) You can use Python 3

In walking_ simulation.py

Then put all the del get_ XX [:] with get_ xx.clear ()

(2) Or restart walking_ simulation.py

I have this kind of mistake sometimes

**Comment by raess1** [comment]
Thanks Python 3 solved the error. 👍 
But when I run: rosservice call /robot_mode "cmd: 1"
Nothing happends. See attched pic.
![2222](https://user-images.githubusercontent.com/6362413/99776551-4bbc4480-2b11-11eb-8193-1abfb722203c.PNG)

**Comment by HitSZwang** [comment]
start step:
roscore
rosrun quadruped_ctrl walking_simulation.py
roslaunch quadruped_ctrl quadruped_ctrl.launch
rosservice call /robot_mode "cmd: 1"
rosservice call /robot_mode "cmd: 4"
rosservice call /gait_type "cmd: 9"

**Comment by raess1** [comment]
Thanks! that worked fine!
