### ISSUE TITLE
@param tauMax : Maximum torque output of the actuator

### ISSUE THREAD

**Issue by raess1** [HitSZwang/mini_cheetah_pybullet#2]
Is the tauMax before or after gearing?
Looking on MiniCheetah.h its defined as cheetah._motorTauMax = 3.f;

I am working on a custom acuator from t-motor AK10-9.
link: https://store-en.tmotor.com/goods.php?id=1030

How do you think I should define tauMax?

**Comment by HitSZwang** [comment]
This motor is a little too luxurious,  you can select motor according to MIT Mini cheetah motor model
If the robot is 9kg, 3. f is enough. if it is bigger, you need to increase it.

**Comment by raess1** [comment]
I am working on a bigger quad :) something between mini and cheetah 3.
trying to import my urdf now and setting up the parameters. 
my robot is around 16-18kg
![image0 png](https://user-images.githubusercontent.com/6362413/99784275-de61e100-2b1b-11eb-87fb-f294c6f3598d.jpg)

**Comment by HitSZwang** [comment]
you can refer the cheetah 3 code

**Comment by raess1** [comment]
Thanks! No luck yet with my own urdf. :-(
