### ISSUE TITLE
你好，请问有用gazebo实现的工程吗？

### ISSUE THREAD

**Issue by xiaoliangstd** [HitSZwang/mini_cheetah_pybullet#4]

**Comment by HitSZwang** [comment]
有，但是正在用，发完论文在考虑是否开源

**Comment by xiaoliangstd** [comment]
你好，我正在尝试移植到gazebo,请问可以给个联系方式嘛，我遇到了一些问题，想看下您复现的效果作一下参考，不知道是否方便，如不方便就算了。感谢！！！或者能否发一段复现视频，我的邮箱是2303335747@qq.com.谢谢，顺便问一下，您使用的gazebo关节控制器是effort_controllers/JointEffortController吗？还是自己写的控制器？谢谢！！

**Comment by HitSZwang** [comment]
效果不如pybullet好，而且存在走不直的现象，稳定性也不好，主要可能还是MPC还有问题，gazebo的关节控制器你可以用effort_controllers / JointEffortController，也可以参考宇树自己写控制器，效果会更好一些
